/**
 * Summit-Ridge-Wealth-Advisors - Frontend App
 * Auto-generated by Module Library Assembler with AI
 */
import React, { useState, useEffect } from 'react';
import { BrowserRouter, Routes, Route, Link, useLocation } from 'react-router-dom';
import { Menu, X } from 'lucide-react';
import './theme.css';
// Page imports
import HomePage from './pages/HomePage';
import AboutPage from './pages/AboutPage';
import ServicesPage from './pages/ServicesPage';
import ContactPage from './pages/ContactPage';
import TestimonialsPage from './pages/TestimonialsPage';
import TeamPage from './pages/TeamPage';


// Mobile menu wrapper component
function NavWrapper({ children }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(typeof window !== 'undefined' && window.innerWidth < 768);
  const location = useLocation();

  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 768);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  useEffect(() => {
    setMenuOpen(false);
  }, [location]);

  return (
    <>
      <nav style={styles.nav}>
        <Link to="/" style={styles.navBrand}>
          <span style={styles.brandText}>Summit Ridge Wealth Advisors</span>
        </Link>
        
        {isMobile ? (
          <button 
            onClick={() => setMenuOpen(!menuOpen)} 
            style={styles.hamburger}
            aria-label="Toggle menu"
          >
            {menuOpen ? <X size={24} /> : <Menu size={24} />}
          </button>
        ) : (
          <>
            <div style={styles.navLinks}>
            <Link to="/" style={styles.navLink}>Home</Link>
            <Link to="/about" style={styles.navLink}>About</Link>
            <Link to="/services" style={styles.navLink}>Services</Link>
            <Link to="/contact" style={styles.navLink}>Contact</Link>
            <Link to="/testimonials" style={styles.navLink}>Testimonials</Link>
            <Link to="/team" style={styles.navLink}>Team</Link>
            </div>
            <div style={styles.navAuth}>

            </div>
          </>
        )}
      </nav>
      
      {isMobile && menuOpen && (
        <div style={styles.mobileMenuOverlay} onClick={() => setMenuOpen(false)}>
          <div style={styles.mobileMenu} onClick={(e) => e.stopPropagation()}>
            <Link to="/" style={styles.mobileNavLink}>Home</Link>
            <Link to="/about" style={styles.mobileNavLink}>About</Link>
            <Link to="/services" style={styles.mobileNavLink}>Services</Link>
            <Link to="/contact" style={styles.mobileNavLink}>Contact</Link>
            <Link to="/testimonials" style={styles.mobileNavLink}>Testimonials</Link>
            <Link to="/team" style={styles.mobileNavLink}>Team</Link>
            <div style={styles.mobileAuthButtons}>

            </div>
          </div>
        </div>
      )}
      {children}
    </>
  );
}

function App() {
  return (
    
    <BrowserRouter>
      <div style={styles.app}>
        <NavWrapper>
          {/* Main Content */}
          <main style={styles.main}>
            <Routes>
              <Route path="/" element={<HomePage />} />
              <Route path="/about" element={<AboutPage />} />
              <Route path="/services" element={<ServicesPage />} />
              <Route path="/contact" element={<ContactPage />} />
              <Route path="/testimonials" element={<TestimonialsPage />} />
              <Route path="/team" element={<TeamPage />} />
            </Routes>
          </main>
          {/* Footer */}
          <footer style={styles.footer}>
            <p>© 2026 Summit-Ridge-Wealth-Advisors. All rights reserved.</p>
          </footer>
        </NavWrapper>
      </div>
    </BrowserRouter>
    
  );
}
const styles = {
  app: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: '#ffffff',
    color: '#1e293b',
    fontFamily: "system-ui, -apple-system, sans-serif",
  },
  nav: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 48px',
    background: '#ffffff',
    borderBottom: '1px solid rgba(10, 22, 40, 0.1)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  navBrand: {
    textDecoration: 'none',
  },
  brandText: {
    fontSize: '20px',
    fontWeight: '400',
    fontFamily: "'Inter', sans-serif",
    color: '#0f172a',
    letterSpacing: '1px',
    textTransform: 'none',
  },
  navLinks: {
    display: 'flex',
    gap: '32px',
  },
  navAuth: {
    display: 'flex',
    alignItems: 'center',
  },
  navLink: {
    color: '#64748b',
    textDecoration: 'none',
    fontSize: '14px',
    fontWeight: '500',
    letterSpacing: '1px',
    textTransform: 'uppercase',
    transition: 'color 0.2s',
  },
  hamburger: {
    background: 'none',
    border: 'none',
    color: '#1e293b',
    cursor: 'pointer',
    padding: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileMenuOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.5)',
    zIndex: 98,
  },
  mobileMenu: {
    position: 'fixed',
    top: '70px',
    left: 0,
    right: 0,
    background: '#ffffff',
    borderBottom: '1px solid rgba(10, 22, 40, 0.1)',
    padding: '16px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    zIndex: 99,
    boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
  },
  mobileNavLink: {
    color: '#1e293b',
    textDecoration: 'none',
    fontSize: '16px',
    fontWeight: '500',
    padding: '12px 0',
    borderBottom: '1px solid rgba(0,0,0,0.05)',
  },
  mobileAuthButtons: {
    paddingTop: '16px',
    borderTop: '1px solid rgba(0,0,0,0.1)',
  },
  main: {
    flex: 1,
  },
  footer: {
    padding: '40px 48px',
    background: '#0f172a',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.6)',
    fontSize: '14px',
    letterSpacing: '1px',
  },
};
export default App;
